### ISSUE TITLE
Crash With Charm Mod's Woodcutter

### ISSUE THREAD

**Issue by DistantDig** [dhyces/ItemBlacklist#1]
So whenever I load up with just item banning and charm, I seem to get a crash whenever I try to use the woodcutter. To recreate it, place a woodcutter down and place any item inside the inventory of the woodcutter and then try to pick it back up again. The version I have is the most up to date of both Item Banning and Charm, Fabric 1.19.2. I should also note that this crash doesn't happen with just Charm loaded.

**Comment by ZeburaBlack** [comment]
This happens with vanilla stonecutters too. From what I was told by another mod developer, it might be caused by making the recipe list unmodifiable

**Comment by QianFuv** [comment]
Will this happen in 1.18.2?

**Comment by dhyces** [comment]
Fixed in 1.19.3 1.2.2+
