### ISSUE TITLE
(Yet another crafting table crash) NPE Crash when attempting to use Pigment Pedestal from Spectrum

### ISSUE THREAD

**Issue by shinji257** [dhyces/ItemBlacklist#5]
When using the Pigment Pedestal from Spectrum a server crash occurs the moment you try to place items in the crafting grid.  Since there is now items there the block gets stuck as Ticking Block Entity and you can no longer enter the chunk until the issue is resolved.  Issues like this at spawn chunks would result in the server failing to boot entirely until the chunk is edited externally or rolled back.

Crash logs:
https://gist.github.com/shinji257/9181f24efe1866ce5894045ccf325cfc
https://gist.github.com/shinji257/b3c1f5d1e6df4e37a07b5adc2948d484

**Comment by dhyces** [comment]
Honestly, this is on them, they're doing something in their code that they shouldn't be, but I can at least put a check on my end to prevent the crash

**Comment by dhyces** [comment]
Fixed with commit 00c32ec and release 1.2.7
